# Generated by Django 5.2.17 on 2026-10-09 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Dr. Sarah Jenkins, MD', max_length=150)),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology')], max_length=50)),
                ('specialization', models.CharField(help_text='e.g. Interventional Cardiology', max_length=150)),
                ('qualification', models.CharField(help_text='e.g. MBBS, MD, FACC', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=5, help_text='Years of clinical practice')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('room_number', models.CharField(default='Room 101, OPD', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Image URL for doctor profile')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 AM', '09:00 AM - 09:30 AM'), ('09:30 AM', '09:30 AM - 10:00 AM'), ('10:00 AM', '10:00 AM - 10:30 AM'), ('10:30 AM', '10:30 AM - 11:00 AM'), ('11:00 AM', '11:00 AM - 11:30 AM'), ('11:30 AM', '11:30 AM - 12:00 PM'), ('02:00 PM', '02:00 PM - 02:30 PM'), ('02:30 PM', '02:30 PM - 03:00 PM'), ('03:00 PM', '03:00 PM - 03:30 PM'), ('03:30 PM', '03:30 PM - 04:00 PM'), ('04:00 PM', '04:00 PM - 04:30 PM'), ('04:30 PM', '04:30 PM - 05:00 PM')], max_length=20)),
                ('reason_for_visit', models.TextField(help_text='Symptoms, health concerns, or consultation reason')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal clinical or admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient')),
            ],
            options={
                'ordering': ['-appointment_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=30)),
                ('heart_rate', models.CharField(blank=True, help_text='e.g. 72 bpm', max_length=30)),
                ('temperature', models.CharField(blank=True, help_text='e.g. 98.6 °F', max_length=30)),
                ('respiratory_rate', models.CharField(blank=True, help_text='e.g. 16 breaths/min', max_length=30)),
                ('diagnosis', models.TextField(help_text='Clinical findings and diagnosis')),
                ('prescription', models.TextField(help_text='Prescribed medications, dosage, and duration')),
                ('doctor_notes', models.TextField(blank=True, help_text='Lifestyle advice, precautions, or lab test requests')),
                ('follow_up_date', models.DateField(blank=True, help_text='Next review visit date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_report', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='appointments.patient')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('doctor', 'appointment_date', 'time_slot'), name='unique_active_doctor_slot'),
        ),
    ]
